### ISSUE TITLE
Can I access IP through mobile phone and view desktop remotely？

### ISSUE THREAD

**Issue by wangdemon** [rviscarra/webrtc-remote-screen#10]

**Comment by rviscarra** [comment]
It depends, you can run it in a desktop and view your desktop from a mobile device on the same LAN, however, if you're not on the same network there's a few things you should consider like NAT traversal and the lack of authentication

**Comment by Duksara** [comment]
@rviscarra hey can you explain to me why do we need NAT traversal for this one? I am running my server using webrtc on a different network and when i try to connect my data channel (which I use for passing mouse commands) works well, but my video stream data is not going through (when i do it in LAN it works). Do you know what is the reason why it doesn't work for the media stream?
